# Generated by Django 5.0.4 on 2024-05-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aastcomppayment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('hours', models.IntegerField(blank=True, db_column='Hours', null=True)),
                ('egp', models.IntegerField(blank=True, db_column='EGP', null=True)),
                ('usd', models.IntegerField(blank=True, db_column='USD', null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=800, null=True)),
            ],
            options={
                'db_table': 'aastcomppayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aastcompregister',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('hours', models.IntegerField(blank=True, db_column='Hours', null=True)),
            ],
            options={
                'db_table': 'aastcompregister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aastpayment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('hours', models.IntegerField(blank=True, db_column='Hours', null=True)),
                ('egp', models.IntegerField(blank=True, db_column='EGP', null=True)),
                ('usd', models.IntegerField(blank=True, db_column='USD', null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=200, null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=200, null=True)),
                ('payment', models.CharField(blank=True, db_column='Payment', max_length=20, null=True)),
            ],
            options={
                'db_table': 'aastpayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aastprereg',
            fields=[
                ('regno', models.IntegerField(db_column='RegNo', primary_key=True, serialize=False)),
                ('program', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=200, null=True)),
            ],
            options={
                'db_table': 'aastprereg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aastreadyregister',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('hours', models.IntegerField(blank=True, db_column='Hours', null=True)),
                ('egp', models.IntegerField(blank=True, db_column='EGP', null=True)),
                ('usd', models.IntegerField(blank=True, db_column='USD', null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=200, null=True)),
            ],
            options={
                'db_table': 'aastreadyregister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aastregister',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('hours', models.IntegerField(blank=True, db_column='Hours', null=True)),
                ('egp', models.IntegerField(blank=True, db_column='EGP', null=True)),
                ('usd', models.IntegerField(blank=True, db_column='USD', null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=30, null=True)),
                ('registration', models.CharField(blank=True, db_column='Registration', max_length=20, null=True)),
            ],
            options={
                'db_table': 'aastregister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AastunregisterTbl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True, unique=True)),
                ('load', models.IntegerField(blank=True, db_column='Load', null=True)),
            ],
            options={
                'db_table': 'aastunregister_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aastwithdraw',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True, unique=True)),
            ],
            options={
                'db_table': 'aastwithdraw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Additiongrouplist',
            fields=[
                ('additiongroupid', models.AutoField(db_column='AdditionGroupID', primary_key=True, serialize=False)),
                ('additiongroup', models.CharField(blank=True, db_column='AdditionGroup', max_length=255, null=True)),
            ],
            options={
                'db_table': 'additiongrouplist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttendTbl',
            fields=[
                ('idlecture', models.AutoField(db_column='IDLecture', primary_key=True, serialize=False)),
                ('doctor', models.CharField(blank=True, db_column='Doctor', max_length=255, null=True)),
                ('coursename', models.CharField(blank=True, db_column='CourseName', max_length=255, null=True)),
                ('lect1', models.IntegerField(blank=True, db_column='Lect1', null=True)),
                ('lect2', models.IntegerField(blank=True, db_column='Lect2', null=True)),
                ('lect3', models.IntegerField(blank=True, db_column='Lect3', null=True)),
                ('lect4', models.IntegerField(blank=True, db_column='Lect4', null=True)),
                ('lect5', models.IntegerField(blank=True, db_column='Lect5', null=True)),
                ('lect6', models.IntegerField(blank=True, db_column='Lect6', null=True)),
                ('lect7', models.IntegerField(blank=True, db_column='Lect7', null=True)),
                ('lect8', models.IntegerField(blank=True, db_column='Lect8', null=True)),
                ('lect9', models.IntegerField(blank=True, db_column='Lect9', null=True)),
                ('lect10', models.IntegerField(blank=True, db_column='Lect10', null=True)),
                ('attendstatus', models.CharField(blank=True, db_column='AttendStatus', max_length=255, null=True)),
                ('attendnote', models.CharField(blank=True, db_column='AttendNote', max_length=255, null=True)),
                ('studentid', models.IntegerField(blank=True, db_column='StudentID', null=True)),
            ],
            options={
                'db_table': 'attend_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorylist',
            fields=[
                ('idcategory', models.AutoField(db_column='IDCategory', primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=255, null=True)),
            ],
            options={
                'db_table': 'categorylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collegelist',
            fields=[
                ('collegeid', models.AutoField(db_column='CollegeID', primary_key=True, serialize=False)),
                ('college', models.CharField(blank=True, db_column='College', max_length=255, null=True)),
            ],
            options={
                'db_table': 'collegelist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companylist',
            fields=[
                ('companyid', models.AutoField(db_column='CompanyID', primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=255, null=True)),
            ],
            options={
                'db_table': 'companylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discountlist',
            fields=[
                ('discountid', models.AutoField(db_column='DiscountID', primary_key=True, serialize=False)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=255, null=True)),
            ],
            options={
                'db_table': 'discountlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discsectorlist',
            fields=[
                ('discsectorid', models.AutoField(db_column='DiscSectorID', primary_key=True, serialize=False)),
                ('discsector', models.CharField(blank=True, db_column='DiscSector', max_length=255, null=True)),
            ],
            options={
                'db_table': 'discsectorlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraduationTbl',
            fields=[
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('regno', models.FloatField(db_column='RegNo', primary_key=True, serialize=False)),
                ('pincode', models.IntegerField(blank=True, db_column='PinCode', null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('major', models.CharField(blank=True, db_column='Major', max_length=255, null=True)),
                ('gpa', models.CharField(blank=True, db_column='GPA', max_length=255, null=True)),
                ('semester', models.CharField(blank=True, db_column='Semester', max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=255, null=True)),
                ('program', models.CharField(blank=True, db_column='Program', max_length=255, null=True)),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=255, null=True)),
                ('discsector', models.CharField(blank=True, db_column='DiscSector', max_length=255, null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=255, null=True)),
                ('discountrate', models.CharField(blank=True, db_column='DiscountRate', max_length=255, null=True)),
                ('job_field', models.CharField(blank=True, db_column='Job Field', max_length=255, null=True)),
                ('studylocation', models.CharField(blank=True, db_column='StudyLocation', max_length=255, null=True)),
                ('sponsor', models.CharField(blank=True, db_column='Sponsor', max_length=255, null=True)),
            ],
            options={
                'db_table': 'graduation_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grouplist',
            fields=[
                ('majorid', models.AutoField(db_column='MajorID', primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, db_column='Group', max_length=255, null=True)),
            ],
            options={
                'db_table': 'grouplist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobfieldlist',
            fields=[
                ('jobfieldid', models.AutoField(db_column='JobFieldID', primary_key=True, serialize=False)),
                ('jobfield', models.CharField(blank=True, db_column='JobField', max_length=255, null=True)),
            ],
            options={
                'db_table': 'jobfieldlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Majorlist',
            fields=[
                ('majorid', models.AutoField(db_column='MajorID', primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, db_column='Group', max_length=255, null=True)),
            ],
            options={
                'db_table': 'majorlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nationalitylist',
            fields=[
                ('nationalid', models.AutoField(db_column='NationalID', primary_key=True, serialize=False)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nationalitylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professorslist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
            ],
            options={
                'db_table': 'professorslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programlist',
            fields=[
                ('programid', models.AutoField(db_column='ProgramID', primary_key=True, serialize=False)),
                ('programname', models.CharField(blank=True, db_column='ProgramName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'programlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staffevaluation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('studentname', models.CharField(blank=True, max_length=200, null=True)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.CharField(blank=True, db_column='Employee', max_length=200, null=True)),
                ('q1', models.IntegerField(blank=True, db_column='Q1', null=True)),
                ('q2', models.IntegerField(blank=True, db_column='Q2', null=True)),
                ('q3', models.IntegerField(blank=True, db_column='Q3', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('semester', models.CharField(blank=True, db_column='Semester', max_length=20, null=True)),
            ],
            options={
                'db_table': 'staffevaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentaffairslist',
            fields=[
                ('employeesid', models.AutoField(db_column='EmployeesID', primary_key=True, serialize=False)),
                ('studentaffairs', models.CharField(blank=True, db_column='StudentAffairs', max_length=255, null=True)),
                ('moodle_user', models.CharField(blank=True, db_column='Moodle_User', max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('manager', models.CharField(blank=True, db_column='Manager', max_length=50, null=True)),
            ],
            options={
                'db_table': 'studentaffairslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsTbl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('engname', models.CharField(db_column='EngName', max_length=255)),
                ('arabicname', models.CharField(db_column='ArabicName', max_length=255)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('pincode', models.CharField(blank=True, db_column='PinCode', max_length=255, null=True)),
                ('initialreg', models.CharField(blank=True, db_column='InitialReg', max_length=255, null=True)),
                ('prelevel', models.CharField(blank=True, db_column='PreLevel', max_length=255, null=True)),
                ('term', models.CharField(db_column='Term', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=255)),
                ('status', models.CharField(db_column='Status', max_length=255)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('onlineadmission', models.CharField(blank=True, db_column='OnlineAdmission', max_length=255, null=True)),
                ('onlinenote', models.TextField(blank=True, db_column='OnlineNote', null=True)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('ms_team_mail', models.CharField(blank=True, db_column='MS_Team_Mail', max_length=30, null=True)),
                ('ms_team_pass', models.CharField(blank=True, db_column='MS_Team_Pass', max_length=20, null=True)),
                ('interview', models.DateTimeField(blank=True, db_column='Interview', null=True)),
                ('compresult', models.CharField(blank=True, db_column='CompResult', max_length=255, null=True)),
                ('gpa', models.CharField(blank=True, db_column='GPA', max_length=255, null=True)),
                ('discregister', models.CharField(blank=True, db_column='DiscRegister', max_length=255, null=True)),
                ('graduatesem', models.CharField(blank=True, db_column='GraduateSem', max_length=255, null=True)),
                ('studylocation', models.CharField(db_column='StudyLocation', max_length=255)),
                ('sponsor', models.CharField(blank=True, db_column='Sponsor', max_length=255, null=True)),
                ('coordinator', models.CharField(blank=True, db_column='Coordinator', max_length=255, null=True)),
                ('emergencyphone', models.CharField(blank=True, db_column='EmergencyPhone', max_length=255, null=True)),
                ('marketing', models.CharField(blank=True, db_column='Marketing', max_length=255, null=True)),
                ('intakesemester', models.CharField(blank=True, db_column='IntakeSemester', max_length=255, null=True)),
                ('amatresult', models.CharField(blank=True, db_column='AMATResult', max_length=255, null=True)),
                ('toeflresult', models.CharField(blank=True, db_column='TOEFLResult', max_length=255, null=True)),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=255, null=True)),
                ('regtime', models.CharField(blank=True, db_column='RegTime', max_length=255, null=True)),
                ('wd_we', models.CharField(blank=True, db_column='WD_WE', max_length=255, null=True)),
                ('gdmtomba', models.IntegerField(blank=True, db_column='GdmToMba', null=True)),
                ('claim', models.CharField(blank=True, db_column='Claim', max_length=5, null=True)),
                ('company', models.CharField(db_column='Company', max_length=255)),
                ('sms', models.IntegerField(blank=True, db_column='SMS', null=True)),
                ('studylevel', models.IntegerField(blank=True, db_column='StudyLevel', null=True)),
                ('cardfregno', models.IntegerField(blank=True, db_column='CardfRegNo', null=True)),
                ('thesisresult', models.CharField(blank=True, db_column='ThesisResult', max_length=255, null=True)),
                ('regnotes', models.TextField(blank=True, db_column='RegNotes', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=255, null=True)),
                ('majornote', models.CharField(blank=True, db_column='MajorNote', max_length=50, null=True)),
                ('regtype', models.CharField(blank=True, db_column='RegType', max_length=255, null=True)),
                ('educode', models.CharField(blank=True, db_column='Educode', max_length=255, null=True)),
                ('onlinenumber', models.CharField(blank=True, db_column='OnlineNumber', max_length=255, null=True)),
                ('onlinepassword', models.CharField(blank=True, db_column='OnlinePassword', max_length=255, null=True)),
                ('registrationpaid', models.IntegerField(blank=True, db_column='RegistrationPaid', null=True)),
                ('toeflexamfees', models.IntegerField(blank=True, db_column='TOEFLExamFees', null=True)),
                ('amatexamfees', models.IntegerField(blank=True, db_column='AMATExamFees', null=True)),
                ('toeflprepfees', models.IntegerField(blank=True, db_column='TOEFLPrepFees', null=True)),
                ('amatprepfees', models.IntegerField(blank=True, db_column='AMATPrepFees', null=True)),
                ('discsuggest', models.CharField(blank=True, db_column='DiscSuggest', max_length=255, null=True)),
                ('discreason', models.CharField(blank=True, db_column='DiscReason', max_length=255, null=True)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=255, null=True)),
                ('picgraduate', models.IntegerField(blank=True, db_column='PicGraduate', null=True)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=20, null=True)),
                ('budget_cat', models.CharField(blank=True, db_column='Budget_Cat', max_length=255, null=True)),
                ('mary_fname', models.CharField(blank=True, db_column='Mary_FName', max_length=30, null=True)),
                ('mary_lname', models.CharField(blank=True, db_column='Mary_LName', max_length=30, null=True)),
                ('usd', models.CharField(blank=True, db_column='USD', max_length=10, null=True)),
                ('discountrate', models.CharField(blank=True, db_column='DiscountRate', max_length=255, null=True)),
                ('pay_egp', models.IntegerField(blank=True, db_column='Pay_EGP', null=True)),
                ('pay_usd', models.IntegerField(blank=True, db_column='Pay_USD', null=True)),
            ],
            options={
                'db_table': 'students_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblassigntoreq',
            fields=[
                ('idassign', models.AutoField(db_column='IDAssign', primary_key=True, serialize=False)),
                ('assignto', models.CharField(blank=True, db_column='AssignTo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblassigntoreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcategoryreqlist',
            fields=[
                ('idcatreq', models.AutoField(db_column='IDCatReq', primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblcategoryreqlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcitylist',
            fields=[
                ('citylistid', models.AutoField(db_column='CityListID', primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, db_column='CityName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tblcitylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcompexamanswers',
            fields=[
                ('regno', models.IntegerField(db_column='RegNo', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=254, null=True)),
                ('started', models.CharField(blank=True, db_column='Started', max_length=254, null=True)),
                ('completed', models.CharField(blank=True, db_column='Completed', max_length=254, null=True)),
                ('time_taken', models.CharField(blank=True, db_column='Time_taken', max_length=254, null=True)),
                ('q1', models.TextField(blank=True, db_column='Q1', null=True)),
                ('q2', models.TextField(blank=True, db_column='Q2', null=True)),
                ('q3', models.TextField(blank=True, db_column='Q3', null=True)),
                ('q4', models.TextField(blank=True, db_column='Q4', null=True)),
                ('q5', models.TextField(blank=True, db_column='Q5', null=True)),
                ('q6', models.TextField(blank=True, db_column='Q6', null=True)),
                ('q7', models.TextField(blank=True, db_column='Q7', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblcompexamanswers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldbapublish',
            fields=[
                ('publishid', models.AutoField(db_column='PublishID', primary_key=True, serialize=False)),
                ('publishname', models.CharField(blank=True, db_column='PublishName', max_length=255, null=True)),
                ('publishlocation', models.CharField(blank=True, db_column='PublishLocation', max_length=255, null=True)),
                ('publishdata', models.CharField(blank=True, db_column='PublishData', max_length=255, null=True)),
                ('publishdate', models.DateTimeField(blank=True, db_column='PublishDate', null=True)),
                ('publishstatus', models.IntegerField(blank=True, db_column='PublishStatus', null=True)),
                ('publishlink', models.TextField(blank=True, db_column='PublishLink', null=True)),
            ],
            options={
                'db_table': 'tbldbapublish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldbathesis',
            fields=[
                ('thesisid', models.AutoField(db_column='ThesisID', primary_key=True, serialize=False)),
                ('thesisname', models.CharField(blank=True, db_column='ThesisName', max_length=255, null=True)),
                ('supervisor1', models.IntegerField(blank=True, db_column='Supervisor1', null=True)),
                ('supervisor2', models.IntegerField(blank=True, db_column='Supervisor2', null=True)),
                ('supervisor3', models.IntegerField(blank=True, db_column='Supervisor3', null=True)),
                ('supervisor4', models.IntegerField(blank=True, db_column='Supervisor4', null=True)),
                ('internalaudit', models.IntegerField(blank=True, db_column='InternalAudit', null=True)),
                ('externalaudit', models.IntegerField(blank=True, db_column='ExternalAudit', null=True)),
                ('deliverydate', models.DateTimeField(blank=True, db_column='DeliveryDate', null=True)),
                ('discusdate', models.DateTimeField(blank=True, db_column='DiscusDate', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('thesislink', models.TextField(blank=True, db_column='ThesisLink', null=True)),
            ],
            options={
                'db_table': 'tbldbathesis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldeanreg',
            fields=[
                ('iddean', models.AutoField(db_column='IDDean', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('approveal', models.CharField(blank=True, db_column='Approveal', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbldeanreg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbledunotes',
            fields=[
                ('eduid', models.AutoField(db_column='EduID', primary_key=True, serialize=False)),
                ('studentid', models.IntegerField(blank=True, db_column='StudentID', null=True)),
                ('educationnote', models.TextField(blank=True, db_column='EducationNote', null=True)),
                ('employee', models.CharField(blank=True, db_column='Employee', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbledunotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbledureq',
            fields=[
                ('idedu', models.AutoField(db_column='IDEdu', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('approveal', models.CharField(blank=True, db_column='Approveal', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbledureq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblestimated',
            fields=[
                ('estid', models.AutoField(db_column='EstID', primary_key=True, serialize=False)),
                ('estimatedno', models.IntegerField(blank=True, db_column='EstimatedNo', null=True)),
                ('estsemester', models.CharField(blank=True, db_column='EstSemester', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblestimated',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblfinreq',
            fields=[
                ('idfin', models.AutoField(db_column='IDFin', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('approveal', models.CharField(blank=True, db_column='Approveal', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblfinreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblgpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('gpa', models.DecimalField(blank=True, db_column='GPA', decimal_places=0, max_digits=10, null=True)),
                ('achievement', models.IntegerField(blank=True, db_column='Achievement', null=True)),
                ('program', models.CharField(blank=True, db_column='Program', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tblgpa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblitreq',
            fields=[
                ('idit', models.AutoField(db_column='IDIT', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('approveal', models.CharField(blank=True, db_column='Approveal', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblitreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmissinggradpapers',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True, unique=True)),
                ('disclaimer', models.CharField(blank=True, db_column='Disclaimer', max_length=10, null=True)),
                ('gradstatement', models.CharField(blank=True, db_column='GradStatement', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tblmissinggradpapers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmissingpapers',
            fields=[
                ('idmissing', models.AutoField(db_column='IDMissing', primary_key=True, serialize=False)),
                ('studentid', models.IntegerField(blank=True, db_column='StudentID', null=True)),
                ('application', models.IntegerField(blank=True, db_column='Application', null=True)),
                ('ba', models.IntegerField(blank=True, db_column='BA', null=True)),
                ('batrans', models.IntegerField(blank=True, db_column='BATrans', null=True)),
                ('pic', models.IntegerField(blank=True, db_column='Pic', null=True)),
                ('idpassport', models.IntegerField(blank=True, db_column='IDPassport', null=True)),
                ('bastatusrpt', models.IntegerField(blank=True, db_column='BAStatusRpt', null=True)),
                ('diploma', models.IntegerField(blank=True, db_column='Diploma', null=True)),
                ('master', models.IntegerField(blank=True, db_column='Master', null=True)),
                ('mastertrans', models.IntegerField(blank=True, db_column='MasterTrans', null=True)),
                ('embassy', models.IntegerField(blank=True, db_column='Embassy', null=True)),
                ('mscstatusrpt', models.IntegerField(blank=True, db_column='MscStatusRpt', null=True)),
                ('toefl', models.IntegerField(blank=True, db_column='TOEFL', null=True)),
                ('initialaccept', models.IntegerField(blank=True, db_column='InitialAccept', null=True)),
                ('completed', models.IntegerField(blank=True, db_column='Completed', null=True)),
            ],
            options={
                'db_table': 'tblmissingpapers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpayment',
            fields=[
                ('studentid', models.IntegerField(blank=True, db_column='StudentID', null=True)),
                ('idbill', models.AutoField(db_column='IDBill', primary_key=True, serialize=False)),
                ('semester', models.CharField(db_column='Semester', max_length=255)),
                ('paymenttype', models.CharField(blank=True, db_column='PaymentType', max_length=255, null=True)),
                ('paymentcat', models.IntegerField(db_column='PaymentCat')),
                ('paydate', models.DateTimeField(blank=True, db_column='PayDate', null=True)),
                ('billnote', models.TextField(blank=True, db_column='BillNote', null=True)),
                ('billno', models.IntegerField(blank=True, db_column='BillNo', null=True)),
                ('feespound', models.IntegerField(blank=True, db_column='FeesPound', null=True)),
                ('feesdollar', models.IntegerField(blank=True, db_column='FeesDollar', null=True)),
                ('employee', models.CharField(blank=True, db_column='Employee', max_length=255, null=True)),
                ('entrydate', models.DateTimeField(blank=True, db_column='EntryDate', null=True)),
                ('register', models.IntegerField(blank=True, db_column='Register', null=True)),
                ('aastpaid', models.IntegerField(blank=True, db_column='AASTPaid', null=True)),
            ],
            options={
                'db_table': 'tblpayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpaymentcatlist',
            fields=[
                ('paymentcatid', models.AutoField(db_column='PaymentCatID', primary_key=True, serialize=False)),
                ('paymentcat', models.CharField(blank=True, db_column='PaymentCat', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblpaymentcatlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblregfollow',
            fields=[
                ('regid', models.AutoField(db_column='RegID', primary_key=True, serialize=False)),
                ('regnote', models.TextField(blank=True, db_column='RegNote', null=True)),
                ('update', models.IntegerField(blank=True, db_column='Update', null=True)),
                ('employee', models.CharField(blank=True, db_column='Employee', max_length=255, null=True)),
                ('notedate', models.DateTimeField(blank=True, db_column='NoteDate', null=True)),
            ],
            options={
                'db_table': 'tblregfollow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblregreq',
            fields=[
                ('idreg', models.AutoField(db_column='IDReg', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('approveal', models.CharField(blank=True, db_column='Approveal', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblregreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblregstatuslist',
            fields=[
                ('regstatusid', models.AutoField(db_column='RegStatusID', primary_key=True, serialize=False)),
                ('regstatus', models.CharField(blank=True, db_column='RegStatus', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblregstatuslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsemesterslist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('semester', models.CharField(blank=True, db_column='Semester', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblsemesterslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblservicespayment',
            fields=[
                ('idserv', models.AutoField(db_column='IDServ', primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, db_column='ID', null=True)),
                ('paymenttype', models.CharField(db_column='PaymentType', max_length=255)),
                ('fees', models.IntegerField(db_column='Fees')),
                ('feestxt', models.CharField(db_column='FeesTxt', max_length=255)),
                ('currancy', models.CharField(db_column='Currancy', max_length=255)),
                ('entrydate', models.DateTimeField(blank=True, db_column='EntryDate', null=True)),
                ('paid', models.IntegerField(blank=True, db_column='Paid', null=True)),
                ('employeesign', models.CharField(blank=True, db_column='EmployeeSign', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblservicespayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsponsorlist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sponsor', models.CharField(blank=True, db_column='Sponsor', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblsponsorlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblstatuslist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('statuslist', models.CharField(blank=True, db_column='StatusList', max_length=255, null=True)),
                ('policy', models.CharField(blank=True, db_column='Policy', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tblstatuslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblstudentsreq',
            fields=[
                ('idrequest', models.AutoField(db_column='IDRequest', primary_key=True, serialize=False)),
                ('term', models.CharField(db_column='Term', max_length=255)),
                ('semester', models.CharField(db_column='Semester', max_length=255)),
                ('description', models.TextField(db_column='Description')),
                ('entrydate', models.DateTimeField(db_column='EntryDate')),
                ('assignto', models.TextField(blank=True, db_column='AssignTo', null=True)),
                ('assignto0', models.TextField(blank=True, db_column='AssignTo0', null=True)),
                ('assigncomment', models.TextField(blank=True, db_column='AssignComment', null=True)),
                ('receivedate', models.DateTimeField(blank=True, db_column='ReceiveDate', null=True)),
                ('attachment', models.TextField(blank=True, db_column='Attachment', null=True)),
                ('status', models.CharField(db_column='Status', max_length=255)),
                ('statuscomment', models.TextField(blank=True, db_column='StatusComment', null=True)),
                ('studentcall', models.IntegerField(blank=True, db_column='StudentCall', null=True)),
                ('employeesign', models.CharField(blank=True, db_column='EmployeeSign', max_length=255, null=True)),
                ('priority', models.CharField(blank=True, db_column='Priority', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblstudentsreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsubjectslist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('subjectname', models.CharField(blank=True, db_column='SubjectName', max_length=255, null=True)),
                ('subjectcode', models.CharField(blank=True, db_column='SubjectCode', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblsubjectslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsubjectsregister',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('idstudent', models.IntegerField(blank=True, db_column='IDStudent', null=True)),
                ('subjectname', models.IntegerField(blank=True, db_column='SubjectName', null=True)),
                ('doctorname', models.IntegerField(blank=True, db_column='DoctorName', null=True)),
                ('semester', models.CharField(blank=True, db_column='Semester', max_length=255, null=True)),
                ('quarter', models.IntegerField(blank=True, db_column='Quarter', null=True)),
            ],
            options={
                'db_table': 'tblsubjectsregister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsysgroup',
            fields=[
                ('sysid', models.AutoField(db_column='SysID', primary_key=True, serialize=False)),
                ('studentid', models.IntegerField(blank=True, db_column='StudentID', null=True)),
                ('sysgroup', models.CharField(blank=True, db_column='SysGroup', max_length=255, null=True)),
                ('semester', models.IntegerField(blank=True, db_column='Semester', null=True)),
                ('sysnote', models.TextField(blank=True, db_column='SysNote', null=True)),
            ],
            options={
                'db_table': 'tblsysgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblviceedureq',
            fields=[
                ('idviceedu', models.AutoField(db_column='IDViceEdu', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('approveal', models.CharField(blank=True, db_column='Approveal', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblviceedureq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblviceregreq',
            fields=[
                ('idvicest', models.AutoField(db_column='IDViceSt', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('approveal', models.CharField(blank=True, db_column='Approveal', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblviceregreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawTbl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('regno', models.CharField(blank=True, db_column='RegNo', max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, db_column='PinCode', max_length=255, null=True)),
                ('semester', models.CharField(blank=True, db_column='Semester', max_length=255, null=True)),
                ('program', models.CharField(blank=True, db_column='Program', max_length=255, null=True)),
                ('introductory', models.CharField(blank=True, db_column='Introductory', max_length=255, null=True)),
                ('term', models.CharField(blank=True, db_column='Term', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('pay_reg', models.CharField(blank=True, db_column='Pay+Reg', max_length=255, null=True)),
                ('payonly', models.CharField(blank=True, db_column='PayOnly', max_length=255, null=True)),
                ('nonpay', models.CharField(blank=True, db_column='NonPay', max_length=255, null=True)),
                ('major', models.CharField(blank=True, db_column='Major', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('group', models.CharField(blank=True, db_column='Group', max_length=255, null=True)),
                ('wd_we', models.CharField(blank=True, db_column='WD/WE', max_length=255, null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=255, null=True)),
                ('job_field', models.CharField(blank=True, db_column='Job Field', max_length=255, null=True)),
            ],
            options={
                'db_table': 'withdraw_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmajor',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='students.studentstbl')),
                ('major2', models.IntegerField(blank=True, db_column='Major2', null=True)),
                ('week', models.CharField(blank=True, db_column='Week', max_length=255, null=True)),
                ('majornote', models.TextField(blank=True, db_column='MajorNote', null=True)),
            ],
            options={
                'db_table': 'tblmajor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblworkinfo',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='students.studentstbl')),
                ('company', models.CharField(blank=True, db_column='Company', max_length=255, null=True)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tblworkinfo',
                'managed': False,
            },
        ),
    ]
