# Generated by Django 5.0.4 on 2024-05-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylist',
            options={'managed': False, 'verbose_name': 'Category List', 'verbose_name_plural': 'Categories List'},
        ),
        migrations.AlterModelOptions(
            name='collegelist',
            options={'managed': False, 'verbose_name': 'College List', 'verbose_name_plural': 'Colleges List'},
        ),
        migrations.AlterModelOptions(
            name='majorlist',
            options={'managed': False, 'verbose_name': 'Major List', 'verbose_name_plural': 'Majors List'},
        ),
        migrations.AlterModelOptions(
            name='nationalitylist',
            options={'managed': False, 'verbose_name': 'Nationality List', 'verbose_name_plural': 'Nationalities List'},
        ),
        migrations.AlterModelOptions(
            name='programlist',
            options={'managed': False, 'verbose_name': 'Program List', 'verbose_name_plural': 'Program List'},
        ),
        migrations.AlterModelOptions(
            name='studentaffairslist',
            options={'managed': False, 'verbose_name': 'Student Affairs List', 'verbose_name_plural': 'Student Affairs List'},
        ),
        migrations.AlterModelOptions(
            name='studentstbl',
            options={'managed': False, 'verbose_name': 'Student Table', 'verbose_name_plural': 'Students Table'},
        ),
        migrations.AlterModelOptions(
            name='tblcitylist',
            options={'managed': False, 'verbose_name': 'City List', 'verbose_name_plural': 'Cities List'},
        ),
        migrations.AlterModelOptions(
            name='tblsemesterslist',
            options={'managed': False, 'verbose_name': 'Semester List', 'verbose_name_plural': 'Semesters List'},
        ),
        migrations.AlterModelOptions(
            name='tblstatuslist',
            options={'managed': False, 'verbose_name': 'Status List', 'verbose_name_plural': 'Status List'},
        ),
        migrations.AlterModelOptions(
            name='tblsubjectslist',
            options={'managed': False, 'verbose_name': 'Subject List', 'verbose_name_plural': 'Subjects List'},
        ),
    ]
