# Generated by Django 5.0.4 on 2024-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblacademicdegreelist',
            fields=[
                ('academicdegreelistid', models.AutoField(db_column='AcademicDegreeListID', primary_key=True, serialize=False)),
                ('academicdegree', models.CharField(blank=True, db_column='AcademicDegree', max_length=50, null=True)),
                ('hourcost', models.DecimalField(blank=True, db_column='HourCost', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tblacademicdegreelist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblacademicmajorlist',
            fields=[
                ('academicmajorlistid', models.AutoField(db_column='AcademicMajorListID', primary_key=True, serialize=False)),
                ('academicmajor', models.CharField(blank=True, db_column='AcademicMajor', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblacademicmajorlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblattendance',
            fields=[
                ('attendanceid', models.AutoField(db_column='AttendanceID', primary_key=True, serialize=False)),
                ('lectureday', models.DecimalField(blank=True, db_column='LectureDay', decimal_places=0, max_digits=10, null=True)),
                ('lecturedate', models.DateField(blank=True, db_column='LectureDate', null=True)),
                ('timefrom', models.TimeField(blank=True, db_column='TimeFrom', null=True)),
                ('timeto', models.TimeField(blank=True, db_column='TimeTo', null=True)),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
            ],
            options={
                'db_table': 'tblattendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblbank',
            fields=[
                ('bankid', models.AutoField(db_column='BankID', primary_key=True, serialize=False)),
                ('bankname', models.DecimalField(blank=True, db_column='BankName', decimal_places=0, max_digits=10, null=True)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=50, null=True)),
                ('accountno', models.CharField(blank=True, db_column='AccountNo', max_length=45, null=True)),
                ('swiftcode', models.CharField(blank=True, db_column='SwiftCode', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblbank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblbanklist',
            fields=[
                ('banklistid', models.AutoField(db_column='BankListID', primary_key=True, serialize=False)),
                ('banklistname', models.CharField(blank=True, db_column='BankListName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblbanklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBudget',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doctors_count', models.IntegerField(blank=True, db_column='Doctors Count', null=True)),
                ('semester', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('teaching_fees', models.FloatField(blank=True, null=True)),
                ('transfer_fees', models.FloatField(blank=True, null=True)),
                ('hall_cost', models.FloatField(blank=True, null=True)),
                ('accommodation_fees', models.FloatField(blank=True, null=True)),
                ('travel_fees', models.FloatField(blank=True, null=True)),
                ('administrative_fess', models.FloatField(blank=True, null=True)),
                ('miscellaneous', models.FloatField(blank=True, null=True)),
                ('advertising', models.FloatField(blank=True, null=True)),
                ('assist_depart_fees', models.FloatField(blank=True, null=True)),
                ('marketing_commission', models.FloatField(blank=True, null=True)),
                ('revenues', models.FloatField(blank=True, null=True)),
                ('expenses', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcategorylist',
            fields=[
                ('categorylistid', models.AutoField(db_column='CategoryListID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='CategoryName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblcategorylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcitylist',
            fields=[
                ('citylistid', models.AutoField(db_column='CityListID', primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, db_column='CityName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tblcitylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcontacts',
            fields=[
                ('contactsid', models.AutoField(db_column='ContactsID', primary_key=True, serialize=False)),
                ('aastid', models.CharField(blank=True, db_column='AASTID', max_length=10, null=True, unique=True)),
                ('portal_pass', models.CharField(blank=True, db_column='Portal_Pass', max_length=50, null=True)),
                ('atitle', models.CharField(blank=True, db_column='Atitle', max_length=20, null=True)),
                ('aname', models.CharField(blank=True, db_column='AName', max_length=50, null=True)),
                ('etitle', models.CharField(blank=True, db_column='ETitle', max_length=20, null=True)),
                ('ename', models.CharField(blank=True, db_column='EName', max_length=50, null=True)),
                ('esurname', models.CharField(blank=True, db_column='ESurname', max_length=45, null=True)),
                ('asurname', models.CharField(blank=True, db_column='ASurname', max_length=45, null=True)),
                ('phone1', models.CharField(blank=True, db_column='Phone1', max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, db_column='Phone2', max_length=15, null=True)),
                ('aast_email', models.CharField(blank=True, db_column='AAST_Email', max_length=50, null=True)),
                ('email1', models.CharField(blank=True, db_column='Email1', max_length=50, null=True)),
                ('email2', models.CharField(blank=True, db_column='Email2', max_length=50, null=True)),
                ('zoom', models.CharField(blank=True, db_column='Zoom', max_length=50, null=True)),
                ('internal_external', models.CharField(blank=True, db_column='Internal-External', max_length=20, null=True)),
                ('city', models.IntegerField(blank=True, db_column='City', null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=50, null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='JobTitle', max_length=50, null=True)),
                ('academicdegree', models.IntegerField(blank=True, db_column='AcademicDegree', null=True)),
                ('academicmajor', models.IntegerField(blank=True, db_column='AcademicMajor', null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
                ('cv', models.TextField(blank=True, db_column='CV', null=True)),
                ('bio', models.TextField(blank=True, db_column='Bio', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=45, null=True)),
                ('paymentdegree', models.IntegerField(db_column='PaymentDegree')),
                ('contreply', models.IntegerField(blank=True, db_column='ContReply', null=True)),
                ('delvexam', models.IntegerField(blank=True, db_column='DelvExam', null=True)),
                ('delvresults', models.IntegerField(blank=True, db_column='DelvResults', null=True)),
                ('otherfess', models.IntegerField(blank=True, db_column='OtherFess', null=True)),
                ('moodle_user', models.CharField(blank=True, db_column='Moodle_User', max_length=20, null=True)),
                ('ms_teams_user', models.CharField(blank=True, db_column='MS_Teams_User', max_length=50, null=True)),
                ('totalfees', models.IntegerField(blank=True, db_column='TotalFees', null=True)),
            ],
            options={
                'db_table': 'tblcontacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcontracts',
            fields=[
                ('contactsid', models.IntegerField(db_column='ContactsID')),
                ('contractsent', models.CharField(blank=True, db_column='ContractSent', max_length=4, null=True)),
                ('contractsentdate', models.DateField(blank=True, db_column='ContractSentDate', null=True)),
                ('contractsid', models.AutoField(db_column='ContractsID', primary_key=True, serialize=False)),
                ('contractdelivered', models.CharField(blank=True, db_column='ContractDelivered', max_length=4, null=True)),
                ('contractdelivereddate', models.DateField(blank=True, db_column='ContractDeliveredDate', null=True)),
            ],
            options={
                'db_table': 'tblcontracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcoursesuggest',
            fields=[
                ('coursesuggestid', models.AutoField(db_column='CourseSuggestID', primary_key=True, serialize=False)),
                ('coursesuggest', models.DecimalField(blank=True, db_column='CourseSuggest', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tblcoursesuggest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbleducode',
            fields=[
                ('educode', models.CharField(db_column='EduCode', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbleducode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblevaluation',
            fields=[
                ('eva_id', models.AutoField(db_column='Eva_id', primary_key=True, serialize=False)),
                ('timetableid', models.IntegerField(blank=True, db_column='TimeTableID', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('q1', models.IntegerField(blank=True, db_column='Q1', null=True)),
                ('q2', models.IntegerField(blank=True, db_column='Q2', null=True)),
                ('q3', models.IntegerField(blank=True, db_column='Q3', null=True)),
                ('q4', models.IntegerField(blank=True, db_column='Q4', null=True)),
                ('q5', models.IntegerField(blank=True, db_column='Q5', null=True)),
                ('q6', models.IntegerField(blank=True, db_column='Q6', null=True)),
                ('q7', models.IntegerField(blank=True, db_column='Q7', null=True)),
                ('q8', models.IntegerField(blank=True, db_column='Q8', null=True)),
                ('q9', models.IntegerField(blank=True, db_column='Q9', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('sent', models.CharField(blank=True, db_column='Sent', max_length=20)),
            ],
            options={
                'db_table': 'tblevaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblevaluationold',
            fields=[
                ('evaluationid', models.AutoField(db_column='EvaluationID', primary_key=True, serialize=False)),
                ('timetableid', models.IntegerField(blank=True, db_column='TimetableID', null=True)),
                ('evacount', models.IntegerField(blank=True, db_column='EvaCount', null=True)),
                ('coursegeneral', models.DecimalField(blank=True, db_column='CourseGeneral', decimal_places=2, max_digits=10, null=True)),
                ('doctorcommit', models.DecimalField(blank=True, db_column='DoctorCommit', decimal_places=2, max_digits=10, null=True)),
                ('doctormethod', models.DecimalField(blank=True, db_column='DoctorMethod', decimal_places=2, max_digits=10, null=True)),
                ('timearrange', models.DecimalField(blank=True, db_column='TimeArrange', decimal_places=2, max_digits=10, null=True)),
                ('coursebalance', models.DecimalField(blank=True, db_column='CourseBalance', decimal_places=2, max_digits=10, null=True)),
                ('doctorcommunicate', models.DecimalField(blank=True, db_column='DoctorCommunicate', decimal_places=2, max_digits=10, null=True)),
                ('courseoutline', models.DecimalField(blank=True, db_column='CourseOutline', decimal_places=2, max_digits=10, null=True)),
                ('materials', models.DecimalField(blank=True, db_column='Materials', decimal_places=2, max_digits=10, null=True)),
                ('doctorgeneral', models.DecimalField(blank=True, db_column='DoctorGeneral', decimal_places=2, max_digits=10, null=True)),
                ('docsubjnotes', models.TextField(blank=True, db_column='DocSubjNotes', null=True)),
                ('empcommunicate', models.DecimalField(blank=True, db_column='EmpCommunicate', decimal_places=2, max_digits=10, null=True)),
                ('emprespond', models.DecimalField(blank=True, db_column='EmpRespond', decimal_places=2, max_digits=10, null=True)),
                ('empsolve', models.DecimalField(blank=True, db_column='EmpSolve', decimal_places=2, max_digits=10, null=True)),
                ('empnotes', models.TextField(blank=True, db_column='EmpNotes', null=True)),
                ('doceva', models.DecimalField(blank=True, db_column='DocEva', decimal_places=2, max_digits=10, null=True)),
                ('docrate', models.CharField(blank=True, db_column='DocRate', max_length=20, null=True)),
                ('subjeva', models.DecimalField(blank=True, db_column='SubjEva', decimal_places=2, max_digits=10, null=True)),
                ('subjrate', models.CharField(blank=True, db_column='SubjRate', max_length=20, null=True)),
                ('empeva', models.DecimalField(blank=True, db_column='EmpEva', decimal_places=2, max_digits=10, null=True)),
                ('emprate', models.CharField(blank=True, db_column='EmpRate', max_length=20, null=True)),
                ('contract', models.CharField(blank=True, db_column='Contract', max_length=200, null=True)),
                ('exams', models.CharField(blank=True, db_column='Exams', max_length=200, null=True)),
                ('results', models.CharField(blank=True, db_column='Results', max_length=200, null=True)),
                ('doctorattend', models.CharField(blank=True, db_column='DoctorAttend', max_length=200, null=True)),
                ('normalresult', models.CharField(blank=True, db_column='NormalResult', max_length=200, null=True)),
                ('evasent', models.CharField(blank=True, db_column='EvaSent', max_length=5, null=True)),
                ('employeeentry', models.CharField(blank=True, db_column='EmployeeEntry', max_length=200, null=True)),
                ('employee', models.CharField(blank=True, db_column='Employee', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tblevaluationold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblexams',
            fields=[
                ('examsid', models.AutoField(db_column='ExamsID', primary_key=True, serialize=False)),
                ('contactsid', models.IntegerField(db_column='ContactsID')),
                ('examdelivered', models.IntegerField(blank=True, db_column='ExamDelivered', null=True)),
                ('examdelivereddate', models.DateField(blank=True, db_column='ExamDeliveredDate', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'tblexams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblgrouplist',
            fields=[
                ('grouplistid', models.AutoField(db_column='GroupListID', primary_key=True, serialize=False)),
                ('groupname', models.CharField(blank=True, db_column='GroupName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tblgrouplist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLailaEvaCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetableid', models.IntegerField(blank=True, db_column='TimeTableID', null=True)),
                ('recommendations', models.TextField(blank=True, db_column='Recommendations', null=True)),
            ],
            options={
                'db_table': 'tbl_laila_eva_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLailaEvaProff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactid', models.IntegerField(blank=True, null=True, unique=True)),
                ('recommendations', models.TextField(blank=True, db_column='Recommendations', null=True)),
            ],
            options={
                'db_table': 'tbl_laila_eva_proff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLailaMsDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(blank=True, db_column='TeamName', max_length=255, null=True)),
                ('filename', models.CharField(blank=True, db_column='FileName', max_length=255, null=True)),
                ('creation_time', models.CharField(blank=True, db_column='Creation_Time', max_length=255, null=True)),
                ('last_write', models.CharField(blank=True, db_column='Last_Write', max_length=255, null=True)),
                ('duration', models.TimeField(blank=True, db_column='Duration', null=True)),
            ],
            options={
                'db_table': 'tbl_laila_ms_duration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmajorlist',
            fields=[
                ('majorlistid', models.AutoField(db_column='MajorListID', primary_key=True, serialize=False)),
                ('majorname', models.CharField(blank=True, db_column='MajorName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblmajorlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpaymentdegreelist',
            fields=[
                ('paymentdegreeid', models.AutoField(db_column='PaymentDegreeID', primary_key=True, serialize=False)),
                ('paymentdegree', models.CharField(blank=True, db_column='PaymentDegree', max_length=15, null=True)),
            ],
            options={
                'db_table': 'tblpaymentdegreelist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblperioudlist',
            fields=[
                ('perioudlistid', models.AutoField(db_column='PerioudListID', primary_key=True, serialize=False)),
                ('perioud', models.CharField(blank=True, db_column='Perioud', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tblperioudlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblprogramlist',
            fields=[
                ('programlistid', models.AutoField(db_column='ProgramListID', primary_key=True, serialize=False)),
                ('programname', models.CharField(blank=True, db_column='ProgramName', max_length=30, null=True)),
            ],
            options={
                'db_table': 'tblprogramlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblresultMissing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('registerno', models.IntegerField(blank=True, db_column='RegisterNo', null=True)),
                ('course_id', models.IntegerField(blank=True, db_column='Course_ID', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'tblresult_missing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblresults',
            fields=[
                ('resultid', models.AutoField(db_column='ResultID', primary_key=True, serialize=False)),
                ('timetableid', models.IntegerField(blank=True, db_column='TimeTableID', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='RegNo', null=True)),
                ('attendance', models.IntegerField(blank=True, db_column='Attendance', null=True)),
                ('project', models.IntegerField(blank=True, db_column='Project', null=True)),
                ('midterm', models.IntegerField(blank=True, db_column='Midterm', null=True)),
                ('final', models.IntegerField(blank=True, db_column='Final', null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
                ('letter', models.CharField(blank=True, db_column='Letter', max_length=5, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'tblresults',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblroomlist',
            fields=[
                ('roomlistid', models.AutoField(db_column='RoomListID', primary_key=True, serialize=False)),
                ('roomname', models.CharField(blank=True, db_column='RoomName', max_length=20, null=True)),
                ('building', models.CharField(blank=True, db_column='Building', max_length=30, null=True)),
                ('location', models.DecimalField(blank=True, db_column='Location', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tblroomlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsemesterlist',
            fields=[
                ('semesterlistid', models.AutoField(db_column='SemesterListID', primary_key=True, serialize=False)),
                ('semestername', models.CharField(blank=True, db_column='SemesterName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblsemesterlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsponsorlist',
            fields=[
                ('sponsorlistid', models.AutoField(db_column='SponsorListID', primary_key=True, serialize=False)),
                ('sponsorname', models.CharField(blank=True, db_column='SponsorName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblsponsorlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsubjectslist',
            fields=[
                ('subjectid', models.AutoField(db_column='SubjectID', primary_key=True, serialize=False)),
                ('subjectcode', models.CharField(blank=True, db_column='SubjectCode', max_length=10, null=True)),
                ('subjectname', models.CharField(blank=True, db_column='SubjectName', max_length=100, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('program', models.CharField(blank=True, db_column='Program', max_length=50, null=True)),
                ('major_name', models.CharField(blank=True, db_column='Major_Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tblsubjectslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltimetable',
            fields=[
                ('timetableid', models.AutoField(db_column='TimeTableID', primary_key=True, serialize=False)),
                ('coursename', models.DecimalField(blank=True, db_column='CourseName', decimal_places=0, max_digits=10, null=True)),
                ('program', models.DecimalField(blank=True, db_column='Program', decimal_places=0, max_digits=10, null=True)),
                ('term', models.CharField(blank=True, db_column='Term', max_length=10, null=True)),
                ('educode', models.CharField(blank=True, db_column='EduCode', max_length=50, null=True)),
                ('location', models.DecimalField(blank=True, db_column='Location', decimal_places=0, max_digits=10, null=True)),
                ('category', models.DecimalField(blank=True, db_column='Category', decimal_places=0, max_digits=10, null=True)),
                ('major', models.DecimalField(blank=True, db_column='Major', decimal_places=0, max_digits=10, null=True)),
                ('group', models.DecimalField(blank=True, db_column='Group', decimal_places=0, max_digits=10, null=True)),
                ('day', models.CharField(blank=True, db_column='Day', max_length=10, null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('week', models.DecimalField(blank=True, db_column='Week', decimal_places=0, max_digits=10, null=True)),
                ('timefrom', models.TimeField(blank=True, db_column='TimeFrom', null=True)),
                ('timeto', models.TimeField(blank=True, db_column='TimeTo', null=True)),
                ('room', models.DecimalField(blank=True, db_column='Room', decimal_places=0, max_digits=10, null=True)),
                ('semester', models.DecimalField(blank=True, db_column='Semester', decimal_places=0, max_digits=10, null=True)),
                ('quarter', models.CharField(blank=True, db_column='Quarter', max_length=4, null=True)),
                ('studytype', models.CharField(blank=True, max_length=200, null=True)),
                ('finalexamdate', models.DateField(blank=True, db_column='FinalExamDate', null=True)),
                ('courseend', models.CharField(blank=True, db_column='CourseEnd', max_length=4, null=True)),
                ('educationnotes', models.CharField(blank=True, db_column='EducationNotes', max_length=255, null=True)),
                ('timetabletype', models.CharField(db_column='TimetableType', max_length=6)),
                ('proffconfirm', models.CharField(blank=True, db_column='ProffConfirm', max_length=7, null=True)),
                ('studentconfirm', models.CharField(blank=True, db_column='StudentConfirm', max_length=7, null=True)),
                ('pgattend', models.CharField(blank=True, db_column='PGAttend', max_length=7, null=True)),
                ('paymentnotes', models.CharField(blank=True, db_column='PaymentNotes', max_length=255, null=True)),
                ('moodleupload', models.CharField(blank=True, db_column='MoodleUpload', max_length=20, null=True)),
                ('teamupload', models.CharField(blank=True, db_column='TeamUpload', max_length=20, null=True)),
                ('evaluationdate', models.DateField(blank=True, db_column='EvaluationDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('paysemester', models.CharField(blank=True, db_column='PaySemester', max_length=30, null=True)),
                ('payquarter', models.CharField(blank=True, db_column='PayQuarter', max_length=10, null=True)),
                ('paylocation', models.CharField(blank=True, db_column='PayLocation', max_length=50, null=True)),
                ('paystatus', models.CharField(blank=True, db_column='PayStatus', max_length=20, null=True)),
                ('paydate', models.DateField(blank=True, db_column='PayDate', null=True)),
                ('teamgroupid', models.CharField(blank=True, db_column='TeamGroupID', max_length=200, null=True)),
                ('teaching_fees', models.FloatField(blank=True, null=True)),
                ('transfer_fees', models.FloatField(blank=True, null=True)),
                ('accommodation_fees', models.FloatField(blank=True, null=True)),
                ('travel_fees', models.FloatField(blank=True, null=True)),
                ('hall_fees', models.FloatField(blank=True, null=True)),
                ('lec_durations', models.TimeField(blank=True, db_column='Lec_Durations', null=True)),
            ],
            options={
                'db_table': 'tbltimetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltimetabletypelist',
            fields=[
                ('idtimetabletype', models.AutoField(db_column='IDTimetableType', primary_key=True, serialize=False)),
                ('timetabletype', models.CharField(blank=True, db_column='TimetableType', max_length=6, null=True)),
            ],
            options={
                'db_table': 'tbltimetabletypelist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblweeklist',
            fields=[
                ('weeklistid', models.AutoField(db_column='WeekListID', primary_key=True, serialize=False)),
                ('weekname', models.CharField(blank=True, db_column='WeekName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblweeklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbusers',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tbusers',
                'managed': False,
            },
        ),
    ]
